//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemedicina.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atencion
    {
        public System.Guid IdAtencion { get; set; }
        public string CodigoAtencion { get; set; }
        public System.Guid IdPersona { get; set; }
        public int IdMedico { get; set; }
        public bool EsProgramada { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Realizada { get; set; }
        public Nullable<int> DuracionEnMinutos { get; set; }
        public string Notas { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Medico Medico { get; set; }
    }
}
