//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemedicina.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaPersona
    {
        public System.Guid IdFichaPersona { get; set; }
        public System.Guid IdPersona { get; set; }
        public string Enfermedad { get; set; }
        public string Descripcion { get; set; }
        public bool EsCronica { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
