//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemedicina.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medico()
        {
            this.Atencions = new HashSet<Atencion>();
        }
    
        public int IdMedico { get; set; }
        public string Nombre { get; set; }
        public int IdTipoMedico { get; set; }
        public int IdEspecialidadMedico { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencions { get; set; }
        public virtual EspecialidadMedico EspecialidadMedico { get; set; }
        public virtual TipoMedico TipoMedico { get; set; }
    }
}
