//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telemedicina.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TelemedicinaEntities : DbContext
    {
        public TelemedicinaEntities()
            : base("name=TelemedicinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atencion> Atencions { get; set; }
        public virtual DbSet<EspecialidadMedico> EspecialidadMedicoes { get; set; }
        public virtual DbSet<TipoMedico> TipoMedicoes { get; set; }
        public virtual DbSet<FichaPersona> FichaPersonas { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Medico> Medicos { get; set; }
    }
}
